- name: Install Stunnel.
  hosts: all
  tasks:
    - name: Copy Stunnel file.
      copy:
        src: /opt/files/stunnel.rpm
        dest: /opt/stunnel.rpm
    - name: Install Stunnel
      command: yum install -y /opt/stunnel.rpm
    - name: Create necessary folders.
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
          - /etc/stunnel
          - /etc/stunnel/certificates
    - name: Place Stunnel.conf
      template:
        src: /opt/redis_role/sentinel_role/templates/stunnel.conf.j2
        dest: "{{ stunnel_conf_path }}"
    - name: Create Stunnel service file.
      template:
        src: /opt/redis_role/sentinel_role/templates/stunnel.service.j2
        dest: "{{ stunnel_service_path }}"
    - name: Copy certificate.
      copy:
        src: /opt/certificates/{{ cert }}
        dest: "{{ cert_path }}"
